# Generated by Django 5.1.4 on 2024-12-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('settlement_type', models.CharField(choices=[('HOTEL', 'hotel'), ('APARTMENTS', 'apartments'), ('HOUSE', 'house'), ('VILLA', 'villa'), ('MOTEL', 'motel')], default='HOTEL', max_length=10)),
                ('price', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
