# Generated by Django 5.1.4 on 2024-12-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Object', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createobject',
            name='image',
            field=models.BinaryField(),
        ),
    ]
