# Generated by Django 5.1.4 on 2024-12-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Object', '0002_alter_createobject_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createobject',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
