# Generated by Django 5.1.4 on 2025-01-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Object', '0003_alter_createobject_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createobject',
            name='image',
            field=models.CharField(max_length=255),
        ),
    ]
