# Generated by Django 5.1.4 on 2024-12-25 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Object', '0003_alter_createobject_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('human_count', models.PositiveIntegerField()),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Object.createobject')),
            ],
        ),
    ]
