# Generated by Django 5.1.4 on 2025-02-11 18:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0005_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='human_count',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
