# Generated by Django 5.1.4 on 2025-03-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0006_alter_booking_human_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
