# Generated by Django 5.1.4 on 2025-04-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_createuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='createuser',
            name='test_bool',
            field=models.BooleanField(default=False),
        ),
    ]
