# Generated by Django 5.1.4 on 2025-04-01 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_createuser_test_bool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createuser',
            name='test_bool',
        ),
    ]
